import { Chess } from 'chess.js';
import sample from '../data/lichess-sample.json';
import { Puzzle, Category, text } from './types';
/** Original teaching positions. Rights: project MIT license. No book extracts. */
const originals: Puzzle[] = [
 {id:'rook-file',fen:'4k3/8/8/p7/8/8/8/R3K3 w - - 0 1',solution:['a1a5'],category:'basics',level:'beginner',source:'original',tags:['capture'],title:text('La torre y la columna','Rook on an open file','A torre e a coluna'),explanation:text('La torre avanza en línea recta. Revisa que no haya piezas entre el origen y el destino.','A rook travels in a straight line. Check that no piece blocks its path.','A torre anda em linha reta. Verifique se há peças bloqueando o caminho.')},
 {id:'rook-rank',fen:'4k3/8/8/8/8/8/8/R5nK w - - 0 1',solution:['a1g1'],category:'basics',level:'beginner',source:'original',tags:['capture'],title:text('Una fila libre','An open rank','Uma fileira livre'),explanation:text('Las torres también capturan horizontalmente. La pieza capturada sale del tablero.','Rooks also capture horizontally. The captured piece leaves the board.','As torres também capturam na horizontal. A peça capturada sai do tabuleiro.')},
 {id:'bishop-diagonal',fen:'4k3/8/8/7p/8/8/8/K1B5 w - - 0 1',solution:['c1h6'],category:'basics',level:'beginner',source:'original',tags:['diagonal'],title:text('Sigue la diagonal','Follow the diagonal','Siga a diagonal'),explanation:text('Un alfil siempre conserva el color de su casilla. En este ejercicio lo desarrollamos hasta h6.','A bishop always stays on the same square color. Here we develop it to h6.','Um bispo permanece na mesma cor de casa. Aqui o desenvolvemos até h6.')},
 {id:'bishop-capture',fen:'4k3/8/7p/8/8/8/8/K1B5 w - - 0 1',solution:['c1h6'],category:'basics',level:'beginner',source:'original',tags:['capture'],title:text('Captura en diagonal','Diagonal capture','Captura diagonal'),explanation:text('Sigue c1-d2-e3-f4-g5-h6. La diagonal está libre y el peón no tiene defensa.','Follow c1-d2-e3-f4-g5-h6. The diagonal is open and the pawn is undefended.','Siga c1-d2-e3-f4-g5-h6. A diagonal está livre e o peão está indefeso.')},
 {id:'knight-jump',fen:'4k3/8/8/8/8/2p5/PPPP4/1N2K3 w - - 0 1',solution:['b1c3'],category:'basics',level:'beginner',source:'original',tags:['capture'],title:text('El salto del caballo','The knight jumps','O salto do cavalo'),explanation:text('El caballo salta sobre otras piezas: dos casillas en una dirección y una perpendicular.','A knight jumps over pieces: two squares in one direction and one perpendicular.','O cavalo salta sobre peças: duas casas numa direção e uma perpendicular.')},
 {id:'pawn-capture',fen:'4k3/8/8/3p4/4P3/8/8/4K3 w - - 0 1',solution:['e4d5'],category:'basics',level:'beginner',source:'original',tags:['capture'],title:text('El peón captura distinto','Pawns capture differently','O peão captura diferente'),explanation:text('Un peón avanza recto, pero captura una casilla en diagonal hacia adelante.','A pawn moves straight forward but captures one square diagonally forward.','O peão avança em linha reta, mas captura uma casa na diagonal para a frente.')},
 {id:'castle-short',fen:'4k3/8/8/8/8/8/8/4K2R w K - 0 1',solution:['e1g1'],category:'basics',level:'beginner',source:'original',tags:['castling'],title:text('Un refugio para el rey','Shelter for the king','Um abrigo para o rei'),explanation:text('Enroca: el rey avanza dos casillas y la torre lo acompaña. No puedes enrocar desde, a través de, ni hacia el jaque.','Castle: the king moves two squares and the rook follows. You cannot castle out of, through, or into check.','Roque: o rei anda duas casas e a torre o acompanha. Não é permitido sair de, passar por ou entrar em xeque.')},
 {id:'en-passant',fen:'4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 2',solution:['e5d6'],category:'basics',level:'easy',source:'original',tags:['enPassant'],title:text('Una oportunidad inmediata','An immediate opportunity','Uma oportunidade imediata'),explanation:text('La captura al paso solo está disponible inmediatamente después del avance doble del peón rival.','En passant is available only immediately after the opposing pawn advances two squares.','A captura en passant só está disponível imediatamente após o avanço duplo do peão adversário.')},
 {id:'promotion',fen:'8/5P1k/5K2/8/8/8/8/8 w - - 0 1',solution:['f7f8q'],category:'endgame',level:'beginner',source:'original',tags:['promotion'],title:text('Un peón, una dama','A pawn becomes a queen','Um peão vira dama'),explanation:text('Al alcanzar la última fila, un peón debe convertirse en dama, torre, alfil o caballo.','On reaching the last rank, a pawn must become a queen, rook, bishop or knight.','Ao chegar à última fileira, um peão deve virar dama, torre, bispo ou cavalo.')},
 {id:'underpromotion',fen:'8/k1P5/2K5/8/8/8/8/8 w - - 0 1',solution:['c7c8r'],category:'endgame',level:'intermediate',source:'original',tags:['underPromotion'],title:text('La dama no siempre es mejor','A queen is not always best','A dama nem sempre é melhor'),explanation:text('Coronar dama aquí ahoga al rey rival. La torre mantiene una casilla de escape y conserva una posición ganadora.','Promoting to a queen here stalemates the opponent. A rook leaves an escape square and preserves a winning position.','Promover a dama aqui causa afogamento. A torre deixa uma casa de fuga e mantém uma posição vencedora.')},
 {id:'back-rank',fen:'6k1/5ppp/8/8/8/8/8/4R1K1 w - - 0 1',solution:['e1e8'],category:'mate',level:'easy',source:'original',tags:['mateIn1','backRankMate'],title:text('La última fila','The back rank','A última fileira'),explanation:text('Los peones del propio rey bloquean sus escapatorias. La torre domina toda la última fila.','The king\'s own pawns block its escape squares. The rook controls the entire back rank.','Os próprios peões do rei bloqueiam suas fugas. A torre domina toda a última fileira.')},
 {id:'queen-net',fen:'7k/8/5KQ1/8/8/8/8/8 w - - 0 1',solution:['g6g7'],category:'mate',level:'easy',source:'original',tags:['mateIn1'],title:text('Rey y dama en equipo','King and queen cooperate','Rei e dama em equipe'),explanation:text('La dama da jaque y cubre las salidas; su rey la protege. Comprueba ambas funciones antes de mover.','The queen checks and covers escape squares; her king protects her. Check both roles before moving.','A dama dá xeque e cobre as fugas; seu rei a protege. Verifique as duas funções antes de mover.')},
 {id:'smothered',fen:'6rk/6pp/7N/8/8/8/8/6K1 w - - 0 1',solution:['h6f7'],category:'mate',level:'intermediate',source:'original',tags:['mateIn1','smotheredMate'],title:text('Mate de la coz','Smothered mate','Mate abafado'),explanation:text('El caballo da jaque sin poder ser bloqueado. Las piezas del propio rey lo dejan sin escapatoria.','A knight\'s check cannot be blocked. The king\'s own pieces leave it without an escape.','O xeque de cavalo não pode ser bloqueado. As próprias peças do rei o deixam sem fuga.')},
 {id:'arabian',fen:'7k/R7/5N2/8/8/8/8/K7 w - - 0 1',solution:['a7h7'],category:'mate',level:'intermediate',source:'original',tags:['mateIn1'],title:text('Torre y caballo','Rook and knight','Torre e cavalo'),explanation:text('El caballo protege h7 y controla g8. La torre completa la red de mate por la columna h.','The knight protects h7 and controls g8. The rook completes the mating net on the h-file.','O cavalo protege h7 e controla g8. A torre completa a rede de mate na coluna h.')},
 {id:'rook-two',fen:'6k1/8/8/8/8/8/R7/1R4K1 w - - 0 1',solution:['a2a7','g8f8','b1b8'],category:'mate',level:'intermediate',source:'original',tags:['mateIn2'],title:text('Piensa dos jugadas adelante','Think two moves ahead','Pense duas jogadas adiante'),explanation:text('Una torre corta la séptima fila; la otra da mate en la octava. La primera jugada limita las escapatorias antes del jaque final.','One rook cuts off the seventh rank; the other mates on the eighth. The first move limits escape squares before the final check.','Uma torre corta a sétima fileira; a outra dá mate na oitava. A primeira jogada limita as fugas antes do xeque final.')},
 {id:'knight-fork',fen:'6k1/3q4/8/3N4/8/8/8/6K1 w - - 0 1',solution:['d5f6','g8f8','f6d7'],category:'fork',level:'intermediate',source:'original',tags:['fork'],title:text('Dos amenazas, una pieza','Two threats, one piece','Duas ameaças, uma peça'),explanation:text('El caballo ataca al rey y a la dama. En esta línea guiada, respondes al movimiento del rey capturando la dama.','The knight attacks both king and queen. In this guided line, answer the king move by taking the queen.','O cavalo ataca o rei e a dama. Nesta linha guiada, responda ao movimento do rei capturando a dama.')},
];
const lichess: Puzzle[] = sample.map(row => {
  const game = new Chess(row.FEN), moves = row.Moves.split(' '), first = moves.shift()!;
  game.move({from:first.slice(0,2),to:first.slice(2,4),promotion:first[4]});
  const rating=Number(row.Rating);
  return {id:`lichess-${row.PuzzleId}`,fen:game.fen(),solution:moves,category:row.category as Category,level:rating<1200?'easy':rating<1800?'intermediate':'advanced',rating,source:'lichess',sourceUrl:`https://lichess.org/training/${row.PuzzleId}`,tags:row.Themes.split(' ')};
});
export const PUZZLES: Puzzle[] = [...originals,...lichess];
export const CATEGORIES: Category[] = ['basics','mate','fork','tactics','endgame','calculation','mixed'];
export function dailyPuzzle(day: string): Puzzle {
  let hash=2166136261;
  for (const char of day) hash=Math.imul(hash^char.charCodeAt(0),16777619)>>>0;
  const pool=PUZZLES.filter(p=>p.level==='easy'||p.level==='intermediate');
  return pool[hash%pool.length];
}
