const {chromium}=require('playwright');
const AxeBuilder=require('@axe-core/playwright').default;
const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'progress/evidence/browser'),ORIGIN='http://localhost:4317';
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json','.wasm':'application/wasm'};
const report={createdAt:new Date().toISOString(),browser:null,checks:[],pageErrors:[],accessibility:[]};
(async()=>{
 await fs.mkdir(OUT,{recursive:true});
 const localCI=process.env.GITHUB_ACTIONS==='true';
 const browser=localCI?await chromium.launch({headless:true}):await chromium.connectOverCDP(process.env.CHROME_CDP_URL||'http://192.168.65.254:9222');report.browser=browser.version();
 const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'es-GT',timezoneId:'America/Guatemala',reducedMotion:'reduce'});
 await context.route(ORIGIN+'/**',async route=>{const pathname=decodeURIComponent(new URL(route.request().url()).pathname);const file=path.resolve(ROOT,'dist',pathname==='/'?'index.html':pathname.slice(1));if(!file.startsWith(path.join(ROOT,'dist')+path.sep)){await route.fulfill({status:403});return;}try{await route.fulfill({status:200,body:await fs.readFile(file),contentType:MIME[path.extname(file)]||'application/octet-stream'});}catch{await route.fulfill({status:404,body:'Not found'});}});
 const page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push(e.message));page.setDefaultTimeout(7000);
 async function check(name,fn){const started=Date.now();try{await fn();report.checks.push({name,result:'PASS',ms:Date.now()-started});console.log('PASS',name);}catch(e){report.checks.push({name,result:'FAIL',error:String(e.message).slice(0,1800)});console.log('FAIL',name,String(e.message).slice(0,500));await page.screenshot({path:path.join(OUT,`failure-${report.checks.length}.png`),fullPage:true}).catch(()=>{});}}
 const goto=async view=>{await page.goto(`${ORIGIN}/#/${view}`,{waitUntil:'networkidle'});};
 const typeMove=async move=>{await page.locator('#typed-move').fill(move);await page.locator('.move-entry button').click();};
 const dragPoints=async(from,to)=>{const source=page.locator(`[data-square="${from}"]`).first(),target=page.locator(`[data-square="${to}"]`).first();await source.scrollIntoViewIfNeeded();const a=await source.boundingBox(),b=await target.boundingBox();assert.ok(a&&b,`Missing drag squares ${from}-${to}`);return {x1:a.x+a.width/2,y1:a.y+a.height/2,x2:b.x+b.width/2,y2:b.y+b.height/2};};
 const mouseDrag=async(from,to)=>{const {x1,y1,x2,y2}=await dragPoints(from,to);await page.mouse.move(x1,y1);await page.mouse.down();await page.mouse.move(x2,y2,{steps:12});await page.mouse.up();};
 const inspectMidDrag=async(from,to)=>{const {x1,y1,x2,y2}=await dragPoints(from,to),mx=(x1+x2)/2,my=(y1+y2)/2;await page.mouse.move(x1,y1);await page.mouse.down();await page.mouse.move(mx,my,{steps:8});await page.waitForTimeout(80);const state=await page.evaluate(({from,mx,my})=>{const source=document.querySelector(`[data-square="${from}"] [data-piece]`);const overlay=[...document.querySelectorAll('body *')].find(el=>{const style=getComputedStyle(el);return style.position==='fixed'&&style.zIndex==='999'&&el.querySelector('[data-piece]');});if(!source||!overlay)return null;const piece=overlay.querySelector('[data-piece]'),r=piece.getBoundingClientRect();return {sourceOpacity:getComputedStyle(source).opacity,overlayOpacity:getComputedStyle(piece).opacity,overlayCenter:{x:r.x+r.width/2,y:r.y+r.height/2},cursor:{x:mx,y:my}};},{from,mx,my});await page.mouse.up();return state;};
 const touchDrag=async(from,to)=>{const board=page.locator('.position-wrap, .board-shell').filter({has:page.locator(`[data-square="${from}"]`)}).first();if(await board.count())await board.scrollIntoViewIfNeeded();const {x1,y1,x2,y2}=await dragPoints(from,to);const cdp=await context.newCDPSession(page),point=(x,y)=>({x,y,radiusX:1,radiusY:1,force:1,id:1});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[point(x1,y1)]});for(let i=1;i<=12;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[point(x1+(x2-x1)*i/12,y1+(y2-y1)*i/12)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});};
 try{
  await check('All nine routes load without untranslated UI keys',async()=>{for(const view of ['home','play','training','academy','progress','library','games','analysis','review']){await goto(view);assert.equal(await page.locator('#root .studio-app').count(),1);const text=await page.locator('main').innerText();assert.ok(!/\bstudio\.[a-z]/i.test(text),`${view}: untranslated studio key`);assert.ok(!text.includes('No pudimos abrir esta vista'),view);}});
  await check('Incorrect quiz does not award completion; correct answer does',async()=>{await goto('academy');await page.getByRole('button',{name:/Lee el tablero/}).click();await page.getByRole('button',{name:'A Alfil',exact:true}).click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('chessy-learning-v1')||'{"lessons":[]}').lessons.length),0);await page.getByRole('button',{name:'B Caballo',exact:true}).click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('chessy-learning-v1')).lessons.length),1);});
  await check('Wrong challenge preserves position; correct solution persists once',async()=>{await goto('training');await typeMove('e1e2');assert.match(await page.locator('.feedback[role="status"]').innerText(),/no es la idea/);await typeMove('a1a5');assert.match(await page.locator('.feedback[role="status"]').innerText(),/Idea encontrada/);await page.reload({waitUntil:'networkidle'});await typeMove('a1a5');const p=await page.evaluate(()=>JSON.parse(localStorage.getItem('chessy-learning-v1')));assert.deepEqual(p.solved,['rook-file']);assert.equal(p.mistakes,1);});
  await check('Hint-assisted play does not award XP',async()=>{await goto('training');await page.getByLabel('Elegir posición').selectOption('rook-rank');await page.getByRole('button',{name:'Una pista',exact:true}).click();await typeMove('a1g1');assert.match(await page.locator('.success-explanation').innerText(),/no suma puntos/);assert.ok(!await page.evaluate(()=>JSON.parse(localStorage.getItem('chessy-learning-v1')).solved.includes('rook-rank')));});
  await check('Mouse drag moves a piece on the play board',async()=>{await page.setViewportSize({width:1440,height:1000});await goto('play');await page.getByRole('button',{name:'Nueva partida',exact:true}).click();await mouseDrag('e2','e4');await page.waitForFunction(()=>/e4/.test(document.querySelector('.play-details')?.textContent||''));assert.match(await page.locator('.play-details').innerText(),/e4/);});
  await check('Dragged piece follows cursor without leaving a visible source ghost',async()=>{await page.setViewportSize({width:1440,height:1000});await goto('play');await page.getByRole('button',{name:'Nueva partida',exact:true}).click();const state=await inspectMidDrag('e2','e4');assert.ok(state,'Missing mid-drag state');assert.equal(state.sourceOpacity,'0');assert.equal(state.overlayOpacity,'1');assert.ok(Math.abs(state.overlayCenter.x-state.cursor.x)<2,`overlay x offset ${state.overlayCenter.x-state.cursor.x}`);assert.ok(Math.abs(state.overlayCenter.y-state.cursor.y)<2,`overlay y offset ${state.overlayCenter.y-state.cursor.y}`);});
  await check('Touch drag works on mobile play and challenge boards',async()=>{await page.setViewportSize({width:390,height:844});await goto('play');await page.getByRole('button',{name:'Nueva partida',exact:true}).click();await touchDrag('e2','e4');await page.waitForFunction(()=>/e4/.test(document.querySelector('.play-details')?.textContent||''));await goto('training');await page.getByLabel('Elegir posición').selectOption('rook-file');await page.locator('.position-wrap').scrollIntoViewIfNeeded();await touchDrag('a1','a5');await page.waitForFunction(()=>/Idea encontrada/.test(document.querySelector('.feedback[role="status"]')?.textContent||''));assert.match(await page.locator('.feedback[role="status"]').innerText(),/Idea encontrada/);await page.setViewportSize({width:1440,height:1000});});
  await check('Native promotion dialog supports rook underpromotion and focus',async()=>{await goto('training');await page.getByLabel('Elegir posición').selectOption('underpromotion');await page.locator('[data-square="c7"]').first().click();await page.locator('[data-square="c8"]').first().click();const dialog=page.getByRole('dialog');await dialog.waitFor();assert.ok(await dialog.evaluate(el=>el.contains(document.activeElement)));await dialog.getByRole('button',{name:'Torre',exact:true}).click();assert.match(await page.locator('.feedback[role="status"]').innerText(),/Idea encontrada/);assert.equal(await page.getByRole('dialog').count(),0);});
  await check('Multi-ply puzzle plays legal opponent reply and accepts final mate',async()=>{await goto('training');await page.getByLabel('Elegir posición').selectOption('rook-two');await typeMove('a2a7');assert.match(await page.locator('.feedback[role="status"]').innerText(),/rival ha respondido/);await typeMove('b1b8');assert.match(await page.locator('.feedback[role="status"]').innerText(),/Idea encontrada/);});
  await check('Black-side Lichess line solves through the same input contract',async()=>{const {Chess}=require('chess.js');const rows=require('../src/data/lichess-sample.json');const row=rows.find(r=>{const b=new Chess(r.FEN),m=r.Moves.split(' ')[0];b.move({from:m.slice(0,2),to:m.slice(2,4),promotion:m[4]});return b.turn()==='b';});await goto('training');await page.getByLabel('Elegir posición').selectOption('lichess-'+row.PuzzleId);assert.match(await page.locator('.board-topline').innerText(),/Juegan negras/);const moves=row.Moves.split(' ').slice(1);for(let i=0;i<moves.length;i+=2)await typeMove(moves[i]);assert.match(await page.locator('.feedback[role="status"]').innerText(),/Idea encontrada/);});
  await check('Language switches and survives reload in English and Portuguese',async()=>{for(const lang of ['en','pt','es']){await goto('home');await page.locator('header select').selectOption(lang);await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('html').getAttribute('lang'),lang);assert.ok(!(await page.locator('main').innerText()).includes('studio.'));}});
  await check('Local play survives training navigation and saves a real PGN game',async()=>{await goto('play');await typeMove('e2e4');await typeMove('e7e5');await page.getByRole('navigation').getByRole('link',{name:'Retos',exact:true}).click();await page.getByRole('navigation').getByRole('link',{name:'Jugar',exact:true}).click();assert.match(await page.locator('.play-details').innerText(),/e4/);await page.getByRole('button',{name:'Guardar partida',exact:true}).click();assert.match(await page.locator('.feedback[role="status"]').innerText(),/guardada/);await page.getByRole('navigation').getByRole('link',{name:'Mis partidas',exact:true}).click();await page.getByText('Partida local',{exact:true}).waitFor();});
  await check('Invalid progress backup is rejected without overwriting progress',async()=>{await goto('progress');const old=await page.evaluate(()=>localStorage.getItem('chessy-learning-v1'));await page.locator('input[type=file]').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":1,"solved":["forged"],"lessons":[],"days":[],"mistakes":0}')});assert.match(await page.locator('.feedback[role="status"]').innerText(),/No se pudo importar/);assert.equal(await page.evaluate(()=>localStorage.getItem('chessy-learning-v1')),old);});
  await check('Progress restore requires explicit confirmation',async()=>{await goto('progress');const old=await page.evaluate(()=>localStorage.getItem('chessy-learning-v1'));const empty='{"version":1,"solved":[],"lessons":[],"days":[],"mistakes":0}';await page.locator('input[type=file]').setInputFiles({name:'chessy.json',mimeType:'application/json',buffer:Buffer.from(empty)});await page.getByRole('button',{name:'Reemplazar progreso',exact:true}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('chessy-learning-v1')),old);await page.getByRole('button',{name:'Reemplazar progreso',exact:true}).click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('chessy-learning-v1')).solved.length),0);});
  await check('Actual Stockfish responds after a legal opening move',async()=>{await goto('play');await page.getByRole('button',{name:'Comenzar partida',exact:true}).click();await typeMove('e2e4');await page.waitForFunction(()=>{const region=document.querySelector('.play-details');return !!region&&/e4/.test(region.innerText)&&/(e5|c5|d5|e6|c6|Nf6|Nc6|d6|g6|b6|a6|h6|b5|a5|g5|h5|f5|f6|Na6|Nh6)/.test(region.innerText);},undefined,{timeout:15000});assert.equal(await page.locator('.feedback.wrong').filter({hasText:'El motor no respondió'}).count(),0);const rows=await page.locator('.play-details').innerText();assert.match(rows,/e4/);assert.match(rows,/(e5|c5|d5|e6|c6|Nf6|Nc6|d6|g6|b6|a6|h6|b5|a5|g5|h5|f5|f6|Na6|Nh6)/);});
  await check('Mobile drawer hides inactive links and closes with Escape',async()=>{await page.setViewportSize({width:390,height:844});await goto('home');assert.equal(await page.locator('aside').evaluate(el=>el.inert),true);await page.getByRole('button',{name:'Abrir navegacion'.replace('navegacion','navegaci\u00f3n'),exact:true}).click();await page.waitForFunction(()=>!document.querySelector('aside').inert);await page.keyboard.press('Escape');await page.waitForFunction(()=>document.querySelector('aside').inert);assert.ok(await page.locator('.mobile-menu').evaluate(el=>el===document.activeElement));await page.setViewportSize({width:1440,height:1000});});
  await check('Reduced motion has no running interface animations',async()=>{await goto('home');const active=await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length);assert.equal(active,0);});
  await check('No horizontal overflow on mobile, tablet and desktop routes',async()=>{for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});for(const view of ['home','play','training','academy','progress','library','games','analysis','review']){await goto(view);const sizes=await page.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth}));if(sizes.scroll>width+1){const overflow=await page.evaluate(()=>Array.from(document.querySelectorAll('main *')).filter(el=>el.getBoundingClientRect().right>innerWidth+1).slice(0,10).map(el=>({tag:el.tagName,cls:el.className,right:el.getBoundingClientRect().right})));throw new Error(`${width}px ${view}: ${sizes.scroll} ${JSON.stringify(overflow)}`);}}}});
  for(const view of ['home','play','training','academy','progress','library','games','analysis','review'])await check(`WCAG 2.1 AA automated scan: ${view}`,async()=>{await page.setViewportSize({width:1440,height:1000});await goto(view);const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();report.accessibility.push({view,violations:results.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,html:n.html,failureSummary:n.failureSummary}))}))});assert.equal(results.violations.length,0,results.violations.map(v=>`${v.id} (${v.nodes.length})`).join('; '));});
  await check('No uncaught JavaScript errors',async()=>assert.deepEqual(report.pageErrors,[]));
  await page.setViewportSize({width:1440,height:1000});await goto('home');await page.screenshot({path:path.join(OUT,'home-desktop.png'),fullPage:true});await goto('academy');await page.screenshot({path:path.join(OUT,'academy-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await goto('home');await page.screenshot({path:path.join(OUT,'home-mobile.png'),fullPage:true});
 }finally{report.passed=report.checks.filter(c=>c.result==='PASS').length;report.failed=report.checks.filter(c=>c.result==='FAIL').length;await fs.writeFile(path.join(OUT,'verification.json'),JSON.stringify(report,null,2));await context.close();if(localCI)await browser.close();}
 console.log(JSON.stringify({passed:report.passed,failed:report.failed,pageErrors:report.pageErrors}));process.exit(report.failed?1:0);
})().catch(e=>{console.error(e.stack||e);process.exit(1)});
