from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
p=ROOT/'scripts/browser-verify.cjs';s=p.read_text().replace("process.env.CI==='true'","process.env.GITHUB_ACTIONS==='true'")
s=s.replace("assert.match(await page.locator('main').innerText(),/Partida local/);", "await page.getByText('Partida local',{exact:true}).waitFor();")
s=s.replace("name:'Comenzar vs IA',exact:true", "name:'Comenzar partida',exact:true")
s=s.replace("return !!region&&/e4/.test(region.innerText)&&document.querySelectorAll('.play-details td').length>=3;", "return !!region&&/e4/.test(region.innerText)&&/(e5|c5|d5|e6|c6|Nf6|Nc6|d6|g6|b6|a6|h6|b5|a5|g5|h5|f5|f6|Na6|Nh6)/.test(region.innerText);")
s=s.replace("{},{timeout:15000}).catch(async()=>{await page.waitForTimeout(4000);});", "undefined,{timeout:15000});")
s=s.replace("assert.ok(sizes.scroll<=width+1,`${width}px ${view}: ${sizes.scroll}`);", "if(sizes.scroll>width+1){const overflow=await page.evaluate(()=>Array.from(document.querySelectorAll('main *')).filter(el=>el.getBoundingClientRect().right>innerWidth+1).slice(0,10).map(el=>({tag:el.tagName,cls:el.className,right:el.getBoundingClientRect().right})));throw new Error(`${width}px ${view}: ${sizes.scroll} ${JSON.stringify(overflow)}`);}")
p.write_text(s)
p=ROOT/'src/styles/studio.css';s=p.read_text();s+='\n.studio-app .text-gray-800{color:#c5d3bb}.book-cover-number{color:#52623d}.book-02 .book-cover-number,.book-05 .book-cover-number{color:#72563b}.book-03 .book-cover-number,.book-06 .book-cover-number{color:#59516c}.hero-board-heading{min-width:0}.hero-board-heading>div{min-width:0}.hero-board-heading .tag{flex-shrink:0}.hero-proof>span{min-width:0}.stat-card{min-width:0}.hero-grid>*{min-width:0}.hero-copy .button-row{max-width:100%}.hero-board-panel{min-width:0}.hero-board{min-width:0}\n';p.write_text(s)
p=ROOT/'src/learning/progress.ts';s=p.read_text();s+='\n/** Longest consecutive run, linear after sorting; bounded imported histories remain cheap. */\nexport function longestStreak(p:Progress):number {let best=0,current=0,previous=Number.NEGATIVE_INFINITY;for(const day of [...new Set(p.days)].sort()){const n=dayNumber(day);current=n-previous===1?current+1:1;best=Math.max(best,current);previous=n;}return best;}\n';p.write_text(s)
p=ROOT/'src/components/studio/ProgressView.tsx';s=p.read_text().replace('localDay, parseProgress, streak, xp','localDay, longestStreak, parseProgress, streak, xp');s=s.replace("progress.days.reduce((best,day)=>Math.max(best,streak({...progress,days:progress.days.filter(d=>d<=day)},day)),0)","longestStreak(progress)");p.write_text(s)
