from pathlib import Path
import json
rows={
'brandLine':['Tu siguiente buena jugada.','Your next great move.','Sua próxima grande jogada.'],
'navLabel':['Navegación principal','Main navigation','Navegação principal'],
'home':['Inicio','Overview','Início'], 'play':['Jugar','Play','Jogar'], 'training':['Retos','Challenges','Desafios'], 'academy':['Academia','Academy','Academia'], 'progress':['Mi progreso','My progress','Meu progresso'], 'library':['Biblioteca','Library','Biblioteca'], 'games':['Mis partidas','My games','Minhas partidas'], 'analysis':['Laboratorio','Analysis lab','Laboratório'], 'review':['Revisión','Review','Revisão'],
'workspace':['TU ESPACIO DE AJEDREZ','YOUR CHESS SPACE','SEU ESPAÇO DE XADREZ'], 'tools':['EXPLORA','EXPLORE','EXPLORE'], 'local':['Sin cuenta. En tu dispositivo.','No account. On your device.','Sem conta. No seu dispositivo.'],
'heroEyebrow':['MENOS AZAR. MÁS IDEAS.','LESS GUESSING. MORE INSIGHT.','MENOS ACASO. MAIS IDEIAS.'],
'heroTitle':['Una buena jugada empieza con una buena idea.','A great move starts with a great idea.','Uma grande jogada começa com uma boa ideia.'],
'heroSubtitle':['Entrena tu mirada, entiende la posición y disfruta cada avance. Tu espacio para aprender ajedrez, a tu ritmo.','Train your eye, understand the position, and enjoy every step forward. Your space to learn chess, at your pace.','Treine seu olhar, entenda a posição e aproveite cada avanço. Seu espaço para aprender xadrez, no seu ritmo.'],
'startPractice':['Empezar un reto','Start a challenge','Começar um desafio'], 'exploreAcademy':['Explorar academia','Explore academy','Explorar academia'],
'daily':['Reto del día','Daily challenge','Desafio do dia'], 'dailyHint':['Una posición. Una idea nueva.','One position. One new idea.','Uma posição. Uma nova ideia.'], 'solveDaily':['Resolver el reto','Solve the challenge','Resolver o desafio'],
'yourPath':['Tu siguiente paso','Your next step','Seu próximo passo'], 'continueLearning':['Seguir aprendiendo','Keep learning','Continuar aprendendo'], 'choosePath':['Encuentra tu próxima idea','Find your next idea','Encontre sua próxima ideia'],
'challengeCount':['{{count}} posiciones jugables','{{count}} playable positions','{{count}} posições jogáveis'], 'lessonCount':['{{count}} lecciones originales','{{count}} original lessons','{{count}} lições originais'], 'languages':['3 idiomas, una misma pasión','3 languages, one shared passion','3 idiomas, uma mesma paixão'],
'xp':['Puntos de aprendizaje','Learning points','Pontos de aprendizado'], 'streak':['Días de racha','Day streak','Dias de sequência'], 'solved':['Retos resueltos','Challenges solved','Desafios resolvidos'], 'completed':['Lecciones completadas','Lessons completed','Lições concluídas'],
'practice':['Práctica libre','Free practice','Prática livre'], 'sprint':['Sesión de 5','Five-puzzle session','Sessão de 5'], 'dailyMode':['Diario','Daily','Diário'],
'challengeTitle':['Entrena una idea. Encuentra la jugada.','Train an idea. Find the move.','Treine uma ideia. Encontre a jogada.'],
'challengeSubtitle':['Juega en el tablero o escribe una jugada. Las respuestas del rival se reproducen automáticamente.','Play on the board or type a move. Opponent replies are played automatically.','Jogue no tabuleiro ou digite uma jogada. As respostas adversárias são reproduzidas automaticamente.'],
'all':['Todos','All','Todos'], 'themeLabel':['Tema','Theme','Tema'], 'difficulty':['Nivel','Level','Nível'], 'selectPuzzle':['Elegir posición','Choose a position','Escolher posição'],
'category.basics':['Primeras jugadas','First moves','Primeiras jogadas'], 'category.mate':['Redes de mate','Mating patterns','Redes de mate'], 'category.fork':['Ataques dobles','Double attacks','Ataques duplos'], 'category.tactics':['Visión táctica','Tactical vision','Visão tática'], 'category.endgame':['Finales','Endgames','Finais'], 'category.calculation':['Cálculo profundo','Deep calculation','Cálculo profundo'], 'category.mixed':['Ideas combinadas','Mixed ideas','Ideias combinadas'],
'level.beginner':['Desde cero','First steps','Do zero'], 'level.easy':['Fundamentos','Foundation','Fundamentos'], 'level.intermediate':['Intermedio','Intermediate','Intermediário'], 'level.advanced':['Avanzado','Advanced','Avançado'],
'whiteToMove':['Juegan blancas','White to move','Brancas jogam'], 'blackToMove':['Juegan negras','Black to move','Pretas jogam'], 'moveLabel':['Tu jugada','Your move','Sua jogada'],
'moveHelp':['Origen y destino, por ejemplo e2e4. Para coronar: q, r, b o n.','Origin and destination, for example e2e4. To promote: q, r, b or n.','Origem e destino, por exemplo e2e4. Para promover: q, r, b ou n.'],
'submit':['Jugar','Play move','Jogar'], 'hint':['Una pista','A hint','Uma dica'], 'reveal':['Ver solución','Show solution','Ver solução'], 'retry':['Intentar de nuevo','Try again','Tentar novamente'], 'next':['Siguiente reto','Next challenge','Próximo desafio'], 'previous':['Anterior','Previous','Anterior'],
'feedback.ready':['Observa las amenazas y busca una jugada concreta.','Look at the threats and find a concrete move.','Observe as ameaças e encontre uma jogada concreta.'],
'feedback.wrong':['Es legal, pero no es la idea de esta línea. La posición se conserva: prueba otra opción.','Legal, but not the idea in this line. The position stays unchanged: try another option.','É legal, mas não é a ideia desta linha. A posição é mantida: tente outra opção.'],
'feedback.illegal':['Esa jugada no es legal en esta posición.','That move is not legal in this position.','Essa jogada não é legal nesta posição.'],
'feedback.continue':['¡Bien visto! El rival ha respondido. Continúa la idea.','Well spotted! Your opponent has replied. Continue the idea.','Bem visto! O adversário respondeu. Continue a ideia.'],
'feedback.solved':['¡Idea encontrada!','You found the idea!','Você encontrou a ideia!'],
'firstSquare':['Empieza con la pieza de {{square}}.','Start with the piece on {{square}}.','Comece com a peça em {{square}}.'], 'guidedMove':['Objetivo guiado: {{move}}.','Guided goal: {{move}}.','Objetivo guiado: {{move}}.'],
'line':['La línea de referencia','The reference line','A linha de referência'], 'assisted':['Práctica asistida: no suma puntos.','Assisted practice: no points awarded.','Prática assistida: não soma pontos.'],
'earned':['+20 puntos por tu primera solución','+20 points for your first solution','+20 pontos pela primeira solução'], 'alreadySolved':['Ya completado: sigue practicando sin duplicar puntos.','Already completed: keep practicing without duplicate points.','Já concluído: continue praticando sem duplicar pontos.'],
'source':['Ver posición de origen','View source position','Ver posição de origem'], 'original':['Ejercicio original de Chessy','Original Chessy exercise','Exercício original do Chessy'], 'ratingNote':['Dificultad de la fuente: {{rating}}. No es tu Elo.','Source puzzle rating: {{rating}}. Not your Elo.','Dificuldade da fonte: {{rating}}. Não é seu Elo.'],
'noPuzzles':['No hay posiciones con estos filtros. Prueba otro nivel.','No positions match these filters. Try another level.','Nenhuma posição corresponde aos filtros. Tente outro nível.'],
'sessionDone':['Sesión completada','Session complete','Sessão concluída'], 'sessionSummary':['Has trabajado cinco posiciones. Repite las ideas que te costaron más.','You worked through five positions. Revisit the ideas you found hardest.','Você trabalhou cinco posições. Reveja as ideias mais difíceis.'], 'newSession':['Nueva sesión','New session','Nova sessão'],
'academyEyebrow':['APRENDE. COMPRUEBA. PRACTICA.','LEARN. CHECK. PRACTICE.','APRENDA. CONFIRA. PRATIQUE.'],
'academyTitle':['Entiende el porqué de cada jugada.','Understand the why behind every move.','Entenda o porquê de cada jogada.'],
'academySubtitle':['Seis rutas, lecciones breves y preguntas para transformar ideas en criterio propio. Contenido original creado para Chessy.','Six paths, short lessons, and questions that turn ideas into your own judgment. Original content created for Chessy.','Seis trilhas, lições curtas e perguntas para transformar ideias em seu próprio critério. Conteúdo original criado para Chessy.'],
 'track.fundamentals':['Primeros pasos','First steps','Primeiros passos'], 'track.tactics':['Táctica','Tactics','Tática'], 'track.strategy':['Estrategia','Strategy','Estratégia'], 'track.openings':['Aperturas','Openings','Aberturas'], 'track.endgames':['Finales','Endgames','Finais'], 'track.calculation':['Cálculo','Calculation','Cálculo'],
'readLesson':['Abrir lección','Open lesson','Abrir lição'], 'backAcademy':['Volver a la academia','Back to academy','Voltar à academia'], 'minutes':['{{count}} min','{{count}} min','{{count}} min'], 'keyIdea':['La idea que te llevas','Your key takeaway','A ideia que você leva'], 'checkUnderstanding':['Comprueba tu idea','Check your understanding','Confira sua ideia'],
'answerCorrect':['¡Exacto! Lección completada.','Exactly! Lesson completed.','Exato! Lição concluída.'], 'answerWrong':['Revisa la idea y vuelve a intentarlo.','Review the idea and try again.','Reveja a ideia e tente novamente.'], 'practiceIdea':['Practicar esta idea','Practice this idea','Praticar esta ideia'],
'progressTitle':['Lo que aprendes se queda contigo.','What you learn stays with you.','O que você aprende fica com você.'],
'progressSubtitle':['Tu progreso se guarda en este navegador. No se sincroniza con otros dispositivos. Exporta una copia para conservarlo.','Your progress is stored in this browser. It does not sync across devices. Export a backup to keep it safe.','Seu progresso é salvo neste navegador. Não sincroniza com outros dispositivos. Exporte uma cópia para preservá-lo.'],
'noElo':['Los puntos reconocen práctica y aprendizaje; no son una clasificación Elo ni una certificación.','Points recognize practice and learning; they are not an Elo rating or a certification.','Os pontos reconhecem prática e aprendizado; não são classificação Elo nem certificação.'], 'achievements':['Pequeñas grandes victorias','Small, meaningful wins','Pequenas grandes vitórias'],
'badge.first':['Primera idea','First insight','Primeira ideia'], 'badge.ten':['Diez posiciones','Ten positions','Dez posições'], 'badge.scholar':['Academia completa','Academy complete','Academia completa'], 'badge.streak':['Tres días seguidos','Three days in a row','Três dias seguidos'], 'locked':['Por descubrir','Yet to unlock','A descobrir'], 'unlocked':['Conseguido','Earned','Conquistado'],
'backup':['Tu copia de seguridad','Your backup','Sua cópia de segurança'], 'export':['Exportar progreso','Export progress','Exportar progresso'], 'import':['Importar copia','Import backup','Importar cópia'], 'importConfirm':['Esta copia reemplazará el progreso de este navegador.','This backup will replace progress in this browser.','Esta cópia substituirá o progresso deste navegador.'], 'replace':['Reemplazar progreso','Replace progress','Substituir progresso'], 'cancel':['Cancelar','Cancel','Cancelar'], 'importSuccess':['Copia restaurada correctamente.','Backup restored successfully.','Cópia restaurada com sucesso.'], 'importError':['No se pudo importar. Usa una copia válida de Chessy de menos de 100 KB.','Import failed. Use a valid Chessy backup under 100 KB.','Falha ao importar. Use uma cópia válida do Chessy com menos de 100 KB.'],
'storageWarning':['No se pudo recuperar o guardar el progreso local. Exporta una copia antes de cerrar.','Local progress could not be restored or saved. Export a backup before closing.','Não foi possível recuperar ou salvar o progresso local. Exporte uma cópia antes de fechar.'],
'libraryTitle':['Ideas que merecen otra mirada.','Ideas worth another look.','Ideias que merecem outro olhar.'], 'librarySubtitle':['Una selección de referencias para continuar aprendiendo. Los libros no están incluidos ni sus contenidos reproducidos.','A reading reference shelf for your next step. Books are not included and their contents are not reproduced.','Uma seleção de referências para continuar aprendendo. Os livros não estão incluídos nem seus conteúdos reproduzidos.'], 'findBook':['Buscar en catálogo','Find in catalog','Buscar no catálogo'], 'referenceOnly':['Referencia bibliográfica · sin descargas','Bibliographic reference · no downloads','Referência bibliográfica · sem downloads'],
'book.basics':['Aprendizaje paso a paso','Step-by-step learning','Aprendizado passo a passo'], 'book.strategy':['Comprensión posicional','Positional understanding','Compreensão posicional'], 'book.games':['Aprender de partidas','Learning from games','Aprender com partidas'], 'book.endings':['Técnica de finales','Endgame technique','Técnica de finais'], 'book.thinking':['Pensamiento y cálculo','Thinking and calculation','Pensamento e cálculo'],
'skip':['Saltar al contenido','Skip to content','Pular para o conteúdo'], 'menu':['Abrir navegación','Open navigation','Abrir navegação'], 'close':['Cerrar','Close','Fechar'],
'playTitle':['Tu tablero. Tu próxima idea.','Your board. Your next idea.','Seu tabuleiro. Sua próxima ideia.'], 'playSubtitle':['Juega localmente con otra persona o entrena contra Stockfish. Sin rivales online simulados ni estadísticas inventadas.','Play locally with another person or practice against Stockfish. No simulated online opponents or invented statistics.','Jogue localmente com outra pessoa ou treine contra Stockfish. Sem rivais online simulados ou estatísticas inventadas.'],
'engineError':['El motor no respondió. Tu posición está a salvo; vuelve a intentarlo.','The engine did not respond. Your position is safe; try again.','O motor não respondeu. Sua posição está segura; tente novamente.'],
'saveGame':['Guardar partida','Save game','Salvar partida'], 'gameSaved':['Partida guardada en este navegador.','Game saved in this browser.','Partida salva neste navegador.'], 'saveError':['No se pudo guardar. Exporta el PGN para conservarla.','Could not save. Export the PGN to keep it.','Não foi possível salvar. Exporte o PGN para preservá-la.'], 'exportPgn':['Exportar PGN','Export PGN','Exportar PGN'], 'importPgn':['Importar PGN','Import PGN','Importar PGN'], 'pgnError':['El PGN no es válido o supera 100 KB.','Invalid PGN or file larger than 100 KB.','PGN inválido ou arquivo maior que 100 KB.'], 'pgnReplace':['La partida importada reemplazará la posición actual.','The imported game will replace the current position.','A partida importada substituirá a posição atual.'],
'footer':['Hecho para disfrutar el proceso, no solo el resultado.','Made to enjoy the process, not just the result.','Feito para aproveitar o processo, não apenas o resultado.'],
}
for index,lang in enumerate(['es','en','pt']):
 target=Path('src/locales')/lang/'translation.json'; data=json.loads(target.read_text()); studio={}
 for key,values in rows.items():
  node=studio; parts=key.split('.')
  for part in parts[:-1]: node=node.setdefault(part,{})
  node[parts[-1]]=values[index]
 data['studio']=studio
 data.setdefault('games',{}).update({'colorLabel':['Color de piezas','Piece color','Cor das peças'][index],'resultLabel':['Resultado','Result','Resultado'][index],'timeControlLabel':['Ritmo de juego','Time control','Ritmo de jogo'][index]})
 data['status']['winsResignation']=['{{color}} gana por abandono','{{color}} wins by resignation','{{color}} vence por abandono'][index]
 target.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
